import { z } from 'zod'

/**
 * Zod schema to validate a game from IGDB API.
 */
export const IGDBGameSchema = z.object({
  id: z.number(),
  name: z.string(),
  slug: z.string(),
  summary: z.string().optional(),
  storyline: z.string().optional(),
  age_ratings: z.array(z.number()).optional(),
  aggregated_rating: z.number().optional(),
  aggregated_rating_count: z.number().optional(),
  alternative_names: z.array(z.number()).optional(),
  artworks: z.array(z.number()).optional(),
  bundles: z.array(z.number()).optional(),
  checksum: z.string().optional(),
  collections: z.array(z.number()).optional(),
  cover: z
    .number()
    .or(z.object({ url: z.string().optional() }))
    .optional(),
  created_at: z.number().optional(),
  dlcs: z.array(z.number()).optional(),
  expanded_games: z.array(z.number()).optional(),
  expansions: z.array(z.number()).optional(),
  external_games: z.array(z.number()).optional(),
  first_release_date: z.number().optional(),
  forks: z.array(z.number()).optional(),
  franchise: z.number().optional(),
  franchises: z.array(z.number()).optional(),
  game_engines: z.array(z.number()).optional(),
  game_localizations: z.array(z.number()).optional(),
  game_modes: z.array(z.number()).optional(),
  game_status: z.number().optional(),
  game_type: z.number().optional(),
  genres: z.array(z.number().or(z.object({ name: z.string() }))).optional(),
  hypes: z.number().optional(),
  involved_companies: z.array(z.number()).optional(),
  keywords: z.array(z.number()).optional(),
  language_supports: z.array(z.number()).optional(),
  multiplayer_modes: z.array(z.number()).optional(),
  parent_game: z.number().optional(),
  platforms: z.array(z.number().or(z.object({ name: z.string() }))).optional(),
  player_perspectives: z.array(z.number()).optional(),
  ports: z.array(z.number()).optional(),
  rating: z.number().optional(),
  rating_count: z.number().optional(),
  release_dates: z.array(z.number()).optional(),
  remakes: z.array(z.number()).optional(),
  remasters: z.array(z.number()).optional(),
  screenshots: z.array(z.number().or(z.object({ url: z.string() }))).optional(),
  similar_games: z.array(z.number()).optional(),
  standalone_expansions: z.array(z.number()).optional(),
  story_line: z.string().optional(),
  tags: z.array(z.number()).optional(),
  themes: z.array(z.number()).optional(),
  total_rating: z.number().optional(),
  total_rating_count: z.number().optional(),
  updated_at: z.number().optional(),
  url: z.string().optional(),
  version_parent: z.number().optional(),
  version_title: z.string().optional(),
  videos: z.array(z.number().or(z.object({ video_id: z.string() }))).optional(),
  websites: z.array(z.number()).optional(),
})

export type IGDBGame = z.infer<typeof IGDBGameSchema>
